### ISSUE TITLE
Fails to Install

### ISSUE THREAD

**Issue by AndroidKitKat** [JohnathonNow/arrows-esolang#1]
When installing from pip using `pip3 install arrows-esolang`, I get an error.

Said error:

>  (base) user@host dir
$ pip3 install arrows-esolang
Collecting arrows-esolang
  Using cached https://files.pythonhosted.org/packages/ae/57/2a74d5b57c91bcdcceac90208c75ec5786df5431cfa17ddfce51079411b3/arrows_esolang-0.0.7.tar.gz
Collecting pillow (from arrows-esolang)
  Using cached https://files.pythonhosted.org/packages/5f/4b/8b54ab9d37b93998c81b364557dff9f61972c0f650efa0ceaf470b392740/Pillow-5.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting enum (from arrows-esolang)
  Using cached https://files.pythonhosted.org/packages/0c/4e/1ea357e7783c756bb579333c1e4a026fb331371ee771f616ffedc781e531/enum-0.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user/miniconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/home/user/miniconda3/lib/python3.6/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/home/user/miniconda3/lib/python3.6/distutils/dist.py", line 9, in <module>
        import re
      File "/home/user/miniconda3/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pdw167qy/enum/

**Comment by JohnathonNow** [comment]
Should be good now fam.
